Removed unnecessary Element reference SubClass, which was propably the cause for
java.lang.ClassCastException: org.vesalainen.bcc.SubClass cannot be cast to com.sun.tools.javac.code.Symbol$ClassSymbol